function principle(abbreviation, article) {
    return '<a class="dont-print-url" href="http://www.principles-wiki.net/principles:' + article + '">' + abbreviation + '</a>';
}


var typesData = {
sapt: {
    name: 'The Technician',
    description: '',
    designs: '',
    programming: 'A technical task',
    principlesLiked: [principle('KISS', 'keep_it_simple_stupid'), 
        principle('MIMC', 'more_is_more_complex'),        
        principle('RoE', 'rule_of_explicitness')],
    principlesDisregarded: [principle('UP', 'uniformity_principle')],
    strengths: [],
    suggestions: [],
    furtherReading: [],
},
sapr: {
    name: 'The Construction Manager',
    description: 'Software development is like a construction site. Don\'t make things more complicated than they are, think ahead and plan in a reasonable manner, but get things done.',
    designs: 'Reasonably planned but a bit conservative',
    programming: 'Like managing a construction site. Somethiong has to be built.',
    principlesLiked: [principle('KISS', 'keep_it_simple_stupid'),
        principle('MIMC', 'more_is_more_complex'),
        principle('RoE', 'rule_of_explicitness'),
        principle('LC', 'low_coupling'),
        principle('HC', 'high_cohesion')],
    principlesDisregarded: [principle('GP', 'generalization_principle'),
        principle('PSU', 'principle_of_separate_understandability'),
        principle('TdA/IE', 'tell_don_t_ask_information_expert')],
    strengths: [],
    suggestions: [],
    furtherReading: [],
},
sait: {
    name: 'The Author',
    description: '',
    designs: '',
    programming: 'Like writing a book: a mixture of planning and creativity',
    principlesLiked: [principle('KISS', 'keep_it_simple_stupid'),
        principle('MP', 'model_principle'),
        principle('PSU', 'principle_of_separate_understandability'),
        principle('TdA/IE', 'tell_don_t_ask_information_expert')],
    principlesDisregarded: [],
    strengths: [],
    suggestions: [],
    furtherReading: [],
},
sair: {
    name: 'The Director or The Professor',
    description: '',
    designs: '',
    programming: 'A serious business',
    principlesLiked: [principle('KISS', 'keep_it_simple_stupid'),
        principle('MIMC', 'more_is_more_complex'),
        principle('ML', 'murphy_s_law'),
        principle('MP', 'model_principle'),
        principle('IH/E', 'information_hiding_encapsulation'),
        principle('PSU', 'principle_of_separate_understandability'),
        principle('UP', 'uniformity_principle'),
        principle('TdA/IE', 'tell_don_t_ask_information_expert')],
    principlesDisregarded: [principle('GP', 'generalization_principle')],
    strengths: [],
    suggestions: [],
    furtherReading: [],
},
scpt: {
    name: 'The Craftsman',
    description: 'Software development is a craft and you want to master it.',
    designs: '',
    programming: 'A craft',
    principlesLiked: [principle('KISS', 'keep_it_simple_stupid'),
        principle('RoE', 'rule_of_explicitness'),
        principle('DRY', 'don_t_repeat_yourself'),
        principle('EUHM', 'easy_to_use_and_hard_to_misuse')],
    principlesDisregarded: [principle('MP', 'model_principle'),
        principle('PSU', 'principle_of_separate_understandability'),
        principle('ML', 'murphy_s_law'),
        principle('IH/E', 'information_hiding_encapsulation'),
        principle('UP', 'uniformity_principle'),
        principle('TdA/IE', 'tell_don_t_ask_information_expert')],
    strengths: [],
    suggestions: [],
    furtherReading: [],
},
scpr: {
    name: 'MacGyver or The Fire Fighter',
    description: 'You can fix anything with a string of duct tape. When there is a problem, you are the one to find a simple and efficient solution for it. You don\'t like endless discussions without getting anything done. While others may still be dreaming of a big system which can do anything, while they spent large amouts of time keeping up with the latest hype, you have already solved the problem and begin looking around where the next problem can be fixed. You don\'t know everything but when there is something you cannot solve yourself, you know where to find helpful code snippets in the internet.',
    designs: 'Small, simple and efficient but probably less foresightful',
    programming: 'Problem solving',
    principlesLiked: [principle('KISS', 'keep_it_simple_stupid'),
        principle('RoE', 'rule_of_explicitness'),
        principle('MIMC', 'more_is_more_complex'),
        principle('RoE', 'rule_of_explicitness')],
    principlesDisregarded: [principle('GP', 'generalization_principle'),
        principle('MP', 'model_principle'),
        principle('PSU', 'principle_of_separate_understandability'),
        principle('ML', 'murphy_s_law'),
        principle('TdA/IE', 'tell_don_t_ask_information_expert')],
    strengths: ['You are an efficient problem solver', 'You don\'t loose time in endless discussions', 'You simply get things done'],
    suggestions: ['Try not to loose the big picture', 
        'Your solutions work now pretty well but in the future they may need to be revised. Be careful that all those necessary future changes don\'t add up such that the overall effort is higher than that for the more elaborate solutions of you colleagues.',
        'Don\'t forget to refactor. Otherwise all those simple enhancements may result in something complicated.'],
    furtherReading: ['<a href="http://www.joelonsoftware.com/items/2009/09/23.html">The Duct Tape Programmer</a>',
        '<a href="http://www.jwz.org/doc/worse-is-better.html">Worse is better</a>']
},
scit: {
    name: 'The Poet or The Scientist',
    description: '',
    designs: '',
    programming: 'Full of interesting details',
    principlesLiked: [principle('KISS', 'keep_it_simple_stupid'),
        principle('DRY', 'don_t_repeat_yourself')],
    principlesDisregarded: [],
    strengths: [],
    suggestions: [],
    furtherReading: [],
},
scir: {
    name: 'The Gardener or The Doctor',
    description: 'A piece of software is like a tree. It grows naturally and it needs to be trimmed regularly. By trimming at the right time the right branches, you\'ll get a nice tree that fulfills its purpose.',
    designs: '',
    programming: 'Like growing a tree',
    principlesLiked: [principle('KISS', 'keep_it_simple_stupid'),
        principle('MIMC', 'more_is_more_complex'),
        principle('DRY', 'don_t_repeat_yourself'),
        principle('UP', 'uniformity_principle')],
    principlesDisregarded: [principle('GP', 'generalization_principle')],
    strengths: [],
    suggestions: [],
    furtherReading: [],
},
papt: {
    name: 'The Wizard',
    description: 'Any sufficiently advanced technology is indistinguishable from magic. And software is a particularly nice one. You know even the complicated spells and that\'s for sure: Soon you will become the archmage.',
    designs: '',
    programming: 'Like magic',
    principlesLiked: [principle('GP', 'generalization_principle')],
    principlesDisregarded: [principle('UP', 'uniformity_principle')],
    strengths: [],
    suggestions: [],
    furtherReading: [],
},
papr: {
    name: 'The Engineer',
    description: 'There\'s nothing to fear for an engineer!',
    designs: '',
    programming: 'An engineering discipline',
    principlesLiked: [principle('GP', 'generalization_principle'),
        principle('MIMC', 'more_is_more_complex'),
        principle('ML', 'murphy_s_law')],
    principlesDisregarded: [],
    strengths: [],
    suggestions: [],
    furtherReading: [],
},
pait: {
    name: 'Einstein or The Composer',
    description: '',
    designs: 'Well thought-out and sophisticated but sometimes a bit over the top.',
    programming: 'Infinite',
    principlesLiked: [principle('GP', 'generalization_principle'),
        principle('LC', 'low_coupling'),
        principle('MP', 'model_principle'),
        principle('TdA/IE', 'tell_don_t_ask_information_expert')],
    principlesDisregarded: [principle('KISS', 'keep_it_simple_stupid'),
        principle('RoE', 'rule_of_explicitness'),
        principle('IH/E', 'information_hiding_encapsulation'),
        principle('PSU', 'principle_of_separate_understandability')],
    strengths: [],
    suggestions: [],
    furtherReading: [],
},
pair: {
    name: 'The Architect',
    description: '',
    designs: '',
    programming: 'A task that needs planned thinking',
    principlesLiked: [principle('GP', 'generalization_principle'),
        principle('LC', 'low_coupling'),
        principle('ML', 'murphy_s_law'),
        principle('MP', 'model_principle'),
        principle('IH/E', 'information_hiding_encapsulation'),
        principle('PSU', 'principle_of_separate_understandability'),
        principle('UP', 'uniformity_principle'),
        principle('TdA/IE', 'tell_don_t_ask_information_expert')],
    principlesDisregarded: [principle('KISS', 'keep_it_simple_stupid'),
        principle('RoE', 'rule_of_explicitness')],
    strengths: [],
    suggestions: [],
    furtherReading: [],
},
pcpt: {
    name: 'The Witcher or The Experimentor',
    description: 'You are invincible! Master of the black magic of coding.',
    designs: '',
    programming: 'fun!',
    principlesLiked: [principle('GP', 'generalization_principle')],
    principlesDisregarded: [principle('ML', 'murphy_s_law'),
        principle('IH/E', 'information_hiding_encapsulation'),
        principle('UP', 'uniformity_principle')],
    strengths: [],
    suggestions: [],
    furtherReading: [],
},
pcpr: {
    name: 'The Shaman',
    description: '',
    designs: '',
    programming: 'Voodoo',
    principlesLiked: [principle('GP', 'generalization_principle')],
    principlesDisregarded: [principle('MP', 'model_principle')],
    strengths: [],
    suggestions: [],
    furtherReading: [],
},
pcit: {
    name: 'The Artist',
    description: '',
    designs: '',
    programming: 'An art',
    principlesLiked: [principle('GP', 'generalization_principle'),
        principle('DRY', 'don_t_repeat_yourself')],
    principlesDisregarded: [principle('KISS', 'keep_it_simple_stupid'),
        principle('RoE', 'rule_of_explicitness'),
        principle('ML', 'murphy_s_law')],
    strengths: [],
    suggestions: [],
    furtherReading: [],
},
pcir: {
    name: 'The Clockmaker',
    description: 'A good system works precisely, just like a swiss clockwork. When every tiny cog wheel moves as it is suppose to, you can be sure that you\'ve created a masterpiece.',
    designs: '',
    programming: 'Like creating a beautiful, precise clockwork',
    principlesLiked: [principle('GP', 'generalization_principle'),
        principle('ML', 'murphy_s_law'),
        principle('UP', 'uniformity_principle')],
    principlesDisregarded: [principle('KISS', 'keep_it_simple_stupid'),
        principle('RoE', 'rule_of_explicitness')],
    strengths: [],
    suggestions: [],
    furtherReading: [],
}
};

